"""create tables

Revision ID: 2b60afeceae4
Revises: 4d75a726f529
Create Date: 2023-05-06 02:07:25.096775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b60afeceae4'
down_revision = '4d75a726f529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
