"""create tables

Revision ID: 7a6266c7e873
Revises: 2b60afeceae4
Create Date: 2023-05-06 02:14:52.972595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6266c7e873'
down_revision = '2b60afeceae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
