"""create tables

Revision ID: a4eef82a8a0f
Revises: ebc22814f174
Create Date: 2023-05-06 01:13:46.033118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4eef82a8a0f'
down_revision = 'ebc22814f174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('name', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('activities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('campers', sa.Column('name', sa.String(), nullable=True))
    op.add_column('campers', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('campers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('campers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('signups', sa.Column('camper_id', sa.Integer(), nullable=True))
    op.add_column('signups', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.add_column('signups', sa.Column('time', sa.Integer(), nullable=True))
    op.add_column('signups', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('signups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(op.f('fk_signups_activity_id_activities'), 'signups', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('fk_signups_camper_id_campers'), 'signups', 'campers', ['camper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_signups_camper_id_campers'), 'signups', type_='foreignkey')
    op.drop_constraint(op.f('fk_signups_activity_id_activities'), 'signups', type_='foreignkey')
    op.drop_column('signups', 'updated_at')
    op.drop_column('signups', 'created_at')
    op.drop_column('signups', 'time')
    op.drop_column('signups', 'activity_id')
    op.drop_column('signups', 'camper_id')
    op.drop_column('campers', 'updated_at')
    op.drop_column('campers', 'created_at')
    op.drop_column('campers', 'age')
    op.drop_column('campers', 'name')
    op.drop_column('activities', 'updated_at')
    op.drop_column('activities', 'created_at')
    op.drop_column('activities', 'difficulty')
    op.drop_column('activities', 'name')
    # ### end Alembic commands ###
